---
title: An R Markdown document converted from "microsoft365.ipynb"
output: html_document
---

# Playground for Microsoft 365

Some resources can be found at [Microsoft365R](https://github.com/Azure/Microsoft365R)

## Sending email

This uses your AD user to send an email using the Microsoft365R library

```{r}
library("Microsoft365R")
library(blastula)
```

```{r}
outlb <- get_business_outlook() # get the outlook client, you will need to sign in to your user account, 
                                # for a shiny app this can be a bit more tricky I guess.
```

```{r}
bl_body <- "## Hello!

This is an email message that was generated by the blastula package.

We can use **Markdown** formatting with the `md()` function.

Cheers,

Luke Skywalker"
```

```{r}
bl_em <- compose_email(
    body = md(bl_body),
    footer = md("sent via Microsoft365R")
)
em <- outlb$create_email(bl_em, subject = "Hello from R", to = "Some.User@niva.no")
```

```{r}
em$send()
```

## Working with onedrive

```{r}
odb <- get_business_onedrive(tenant = "niva365") # get the onedrive client, you will need to sign in to user account
```

```{r}
odb$list_items()
```

```{r}
odb$upload_file("somefile.txt", "./somefile.txt")
```

```{r}
odb$list_items()
```

